# Generated by Django 5.2.7 on 2025-10-26 04:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del recuerdo (máximo 200 caracteres)', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción detallada del recuerdo', verbose_name='Descripción')),
                ('image', models.ImageField(help_text='Imagen del recuerdo (JPG, PNG, GIF - máximo 5MB)', upload_to='memories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Imagen')),
                ('date', models.DateField(help_text='Fecha en que ocurrió el recuerdo', verbose_name='Fecha del recuerdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.ForeignKey(help_text='Usuario propietario del recuerdo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recuerdo',
                'verbose_name_plural': 'Recuerdos',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='memories_me_user_id_ec584d_idx')],
            },
        ),
    ]
