# Generated by Django 5.2.7 on 2025-10-26 05:08

import django.core.validators
import memories.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateField(help_text='Fecha en que ocurrió el recuerdo', validators=[memories.validators.validate_memory_date], verbose_name='Fecha del recuerdo'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='description',
            field=models.TextField(help_text='Descripción detallada del recuerdo', validators=[memories.validators.validate_memory_description], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(help_text='Imagen del recuerdo (JPG, PNG, GIF, WEBP - máximo 5MB)', upload_to='memories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), memories.validators.ImageValidator(), memories.validators.FilenameValidator()], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='title',
            field=models.CharField(help_text='Título del recuerdo (máximo 200 caracteres)', max_length=200, validators=[memories.validators.validate_memory_title], verbose_name='Título'),
        ),
    ]
