# Generated by Django 5.2.7 on 2025-10-26 05:47

import django.core.validators
import memories.models
import memories.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_alter_memory_date_alter_memory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(help_text='Imagen del recuerdo (JPG, PNG, GIF, WEBP - máximo 5MB)', upload_to=memories.models.memory_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), memories.validators.ImageValidator()], verbose_name='Imagen'),
        ),
    ]
